--Q51--
SELECT k.TenKhoa
FROM GIAO_VIEN gv join BO_MON bm ON bm.MaBM=gv.MaBM join KHOA k ON k.MaKhoa=bm.MaKhoa
GROUP BY k.MaKhoa,k.MaKhoa
HAVING COUNT(gv.MaGV)>=all(SELECT COUNT(gv2.MaGV)
FROM GIAO_VIEN gv2 join BO_MON bm2 ON bm2.MaBM=gv2.MaBM join KHOA k2 on k2.MaKhoa=bm2.MaKhoa GROUP BY k2.MaKhoa)
--Q52--
SELECT gv.HOTEN
FROM GIAO_VIEN gv join DE_TAI dt ON dt.GVCNDT=gv.MaGV
GROUP BY dt.GVCNDT,gv.HOTEN
HAVING COUNT(dt.MADT)>=all(SELECT COUNT(dt2.MaDT) FROM DE_TAI dt2 GROUP BY dt2.GVCNDT)
--Q53--
SELECT BM.MaBM
FROM BO_MON bm join GIAO_VIEN gv ON gv.MaBM=bm.MaBM
GROUP BY bm.MaBM
HAVING COUNT(gv.MaGV)>=all(SELECT COUNT(gv2.MaGV) FROM BO_MON bm2 join GIAO_VIEN gv2 ON gv2.MaBM=bm2.MaBM GROUP BY bm2.MaBM)
--Q54--
SELECT GV.HoTen,BM.TenBM
FROM GIAO_VIEN gv join THAM_GIA_DT tg ON tg.MaGV=gv.MaGV join BO_MON bm ON bm.MaBM=GV.MaBM
group by tg.MaGV,gv.HoTen, bm.TenBM
HAVING COUNT(DISTINCT tg.MADT)>=all(SELECT COUNT(DISTINCT tg2.MaDT) FROM THAM_GIA_DT tg2 GROUP BY tg2.MaGV)
--Q55--
SELECT GV.HoTen
FROM GIAO_VIEN GV JOIN THAM_GIA_DT TG ON TG.MaGV=GV.MaGV
WHERE GV.MABM='HTTT'
GROUP BY TG.MaGV,GV.HoTen
HAVING COUNT(DISTINCT TG.MaDT)>=ALL(SELECT COUNT(DISTINCT TG2.MaDT) FROM THAM_GIA_DT TG2 GROUP BY TG2.MaGV)



--Q58--
SELECT GV.HoTen
FROM GIAO_VIEN GV JOIN THAM_GIA_DT TG ON GV.MaGV=TG.MaGV JOIN DE_TAI DT ON DT.MaDT=TG.MaDT
WHERE NOT EXISTS (SELECT * FROM CHU_DE CD 
	WHERE NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 JOIN DE_TAI DT2 ON DT2.MaDT=TG2.MaDT 
		WHERE DT2.MaCD=CD.MaCD AND DT2.MaDT=DT.MaDT))
	
--Q59-
SELECT DISTINCT DT.TENDT
FROM THAM_GIA_DT TG JOIN DE_TAI DT ON DT.MaDT=TG.MaDT
WHERE NOT EXISTS (SELECT * FROM GIAO_VIEN GV WHERE GV.MaBM='HTTT' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2  WHERE TG2.MaDT=TG.MaDT AND TG2.MaGV=GV.MaGV))

--Q60--
SELECT DISTINCT DT.TENDT
FROM THAM_GIA_DT TG JOIN DE_TAI DT ON DT.MaDT=TG.MaDT
WHERE NOT EXISTS (SELECT * FROM GIAO_VIEN GV JOIN BO_MON BM ON BM.MaBM=GV.MaBM WHERE BM.TenBM=N'Hệ thống thông tin' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2  WHERE TG2.MaDT=TG.MaDT AND TG2.MaGV=GV.MaGV))

--Q61--
SELECT GV.HoTen
FROM THAM_GIA_DT TG JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV
WHERE NOT EXISTS (SELECT * FROM DE_TAI DT WHERE DT.MaCD='QLGD' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaDT=DT.MaDT AND TG2.MaGV=TG.MaGV))