--Q35--
SELECT distinct gv.Luong
FROM GIAO_VIEN gv
WHERE gv.Luong>=all(SELECT gv2.Luong FROM GIAO_VIEN gv2)
--Q36--
SELECT gv.*
FROM GIAO_VIEN gv
WHERE gv.Luong>=all(SELECT gv2.Luong FROM GIAO_VIEN gv2)
--Q37--
SELECT distinct gv.Luong
FROM GIAO_VIEN gv
WHERE gv.MaBM='MMT' and gv.Luong>=all(SELECT gv2.Luong FROM GIAO_VIEN gv2 WHERE gv2.MaBM='MMT')
--Q38--
SELECT gv.HoTen
FROM GIAO_VIEN gv join BO_MON bm on bm.MaBM=gv.MaBM
WHERE bm.TenBM=N'Hệ thống thông tin' 
and gv.NgSinh<=all(SELECT gv2.NgSinh FROM GIAO_VIEN gv2 join BO_MON bm2 on bm2.MaBM=gv2.MaBM WHERE bm2.TenBM=N'Hệ thống thông tin')
--Q39--
SELECT GV.HoTen
FROM GIAO_VIEN gv join BO_MON bm on gv.MaBM=bm.MaBM join KHOA k on k.MaKhoa=bm.MaKhoa
WHERE k.TenKhoa=N'Công nghệ thông tin'
and year(gv.NgSinh)>=all(SELECT year(gv2.NgSinh) FROM GIAO_VIEN gv2 join BO_MON bm2 on gv2.MaBM=bm2.MaBM join KHOA k2 on k2.MaKhoa=bm2.MaKhoa
WHERE k2.TenKhoa=N'Công nghệ thông tin')
--Q40--
SELECT GV.HoTen, k.TenKhoa
FROM GIAO_VIEN gv join BO_MON bm on gv.MaBM=bm.MaBM join KHOA k on k.MaKhoa=bm.MaKhoa
WHERE gv.Luong>=all(SELECT gv2.Luong FROM GIAO_VIEN gv2)
--Q41--
SELECT gv.HoTen
FROM GIAO_VIEN gv 
group by gv.MaBM, gv.HoTen, gv.Luong
having gv.Luong>=all(SELECT gv2.Luong FROM GIAO_VIEN gv2 group by gv2.MaBM, gv2.Luong having gv2.MaBM=gv.MaBM)
--Q42--
SELECT dt.TenDT
FROM DE_TAI dt
WHERE dt.MaDT not in (SELECT tg.MaDT FROM GIAO_VIEN gv join THAM_GIA_DT tg on tg.MaGV=GV.MaGV WHERE gv.HoTen=N'Nguyễn Hoài An')
--Q43--
SELECT dt.TenDT,gv2.HoTen
FROM DE_TAI dt join GIAO_VIEN gv2 on dt.GVCNDT=gv2.MaGV
WHERE dt.MaDT not in (SELECT tg.MaDT FROM GIAO_VIEN gv join THAM_GIA_DT tg on tg.MaGV=GV.MaGV WHERE gv.HoTen=N'Nguyễn Hoài An')

--Q44--
SELECT gv.HoTen
FROM GIAO_VIEN gv join BO_MON bm on bm.MaBM=gv.MaBM join KHOA k on k.MaKhoa=bm.MaKhoa
WHERE k.TenKhoa=N'Công nghệ thông tin'
and gv.MaGV not in (SELECT tg.MaGV FROM THAM_GIA_DT tg)

--Q45--
SELECT gv.HoTen
FROM GIAO_VIEN gv
WHERE gv.MaGV not in (SELECT tg.MaGV FROM THAM_GIA_DT tg)
--Q46--
SELECT gv.*
FROM GIAO_VIEN gv
WHERE gv.Luong>(SELECT gv2.Luong FROM GIAO_VIEN gv2 WHERE gv2.HoTen=N'Nguyễn Hoài An')
--Q47--
SELECT gv.*
FROM BO_MON bm join GIAO_VIEN gv on bm.TruongBM=gv.MaGV
WHERE gv.MaGV in (SELECT tg.MaGV FROM THAM_GIA_DT tg)
--Q48--
SELECT gv.*
FROM GIAO_VIEN gv
WHERE exists (SELECT * FROM GIAO_VIEN gv2 WHERE gv2.HoTen=gv.HoTen and gv2.GioiTinh=gv.GioiTinh and gv2.MaBM=gv.MaBM and gv2.MaGV!=gv.MaGV)
--Q49--
SELECT gv.*
FROM GIAO_VIEN gv 
WHERE gv.Luong>any(SELECT gv2.Luong FROM GIAO_VIEN gv2 join BO_MON bm2 on bm2.MaBM=gv2.MaBM WHERE bm2.TenBM=N'Công nghệ phần mềm')
--Q50--
SELECT gv.*
FROM GIAO_VIEN gv 
WHERE gv.Luong>all(SELECT gv2.Luong FROM GIAO_VIEN gv2 join BO_MON bm2 on bm2.MaBM=gv2.MaBM WHERE bm2.TenBM=N'Hệ thống thông tin')
--Q51--
SELECT k.TenKhoa
FROM GIAO_VIEN gv join BO_MON bm ON bm.MaBM=gv.MaBM join KHOA k ON k.MaKhoa=bm.MaKhoa
GROUP BY k.MaKhoa,k.MaKhoa
HAVING COUNT(gv.MaGV)>=all(SELECT COUNT(gv2.MaGV)
FROM GIAO_VIEN gv2 join BO_MON bm2 ON bm2.MaBM=gv2.MaBM join KHOA k2 on k2.MaKhoa=bm2.MaKhoa GROUP BY k2.MaKhoa)
--Q52--
SELECT gv.HoTen
FROM GIAO_VIEN gv join DE_TAI dt ON dt.GVCNDT=gv.MaGV
GROUP BY dt.GVCNDT,gv.HoTen
HAVING COUNT(dt.MaDT)>=all(SELECT COUNT(dt2.MaDT) FROM DE_TAI dt2 GROUP BY dt2.GVCNDT)
--Q53--
SELECT BM.MaBM
FROM BO_MON bm join GIAO_VIEN gv ON gv.MaBM=bm.MaBM
GROUP BY bm.MaBM
HAVING COUNT(gv.MaGV)>=all(SELECT COUNT(gv2.MaGV) FROM BO_MON bm2 join GIAO_VIEN gv2 ON gv2.MaBM=bm2.MaBM GROUP BY bm2.MaBM)
--Q54--
SELECT GV.HoTen,BM.TenBM
FROM GIAO_VIEN gv join THAM_GIA_DT tg ON tg.MaGV=gv.MaGV join BO_MON bm ON bm.MaBM=GV.MaBM
group by tg.MaGV,gv.HoTen, bm.TenBM
HAVING COUNT(DISTINCT tg.MaDT)>=all(SELECT COUNT(DISTINCT tg2.MaDT) FROM THAM_GIA_DT tg2 GROUP BY tg2.MaGV)
--Q55--
SELECT GV.HoTen
FROM GIAO_VIEN GV JOIN THAM_GIA_DT TG ON TG.MaGV=GV.MaGV
WHERE GV.MABM='HTTT'
GROUP BY TG.MaGV,GV.HoTen
HAVING COUNT(DISTINCT TG.MaDT)>=ALL(SELECT COUNT(DISTINCT TG2.MaDT) FROM THAM_GIA_DT TG2 GROUP BY TG2.MaGV)
--Q56--
SELECT GV.HoTen,BM.TenBM
FROM GIAO_VIEN GV JOIN BO_MON BM ON BM.MaBM=GV.MaBM JOIN NGUOI_THAN NT ON NT.MaGV=GV.MaGV
GROUP BY NT.MaGV,GV.HoTen,BM.TenBM
HAVING COUNT(NT.HoTen)>=ALL(SELECT COUNT(NT2.HoTen) FROM NGUOI_THAN NT2 GROUP BY NT2.MaGV)
--Q57--
SELECT GV.HoTen
FROM GIAO_VIEN GV JOIN BO_MON BM ON BM.TruongBM=GV.MaGV JOIN DE_TAI DT ON DT.GVCNDT=GV.MaGV
GROUP BY BM.TruongBM,GV.HoTen
HAVING COUNT(DT.GVCNDT)>=ALL(SELECT COUNT(DT2.GVCNDT) FROM BO_MON BM2 JOIN DE_TAI DT2 ON BM2.TruongBM=DT2.GVCNDT GROUP BY BM2.TruongBM)


--Q62--
SELECT DISTINCT GV.HoTen
FROM THAM_GIA_DT TG JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV
WHERE GV.HoTen!=N'Trần Trà Hương' AND 
	NOT EXISTS (SELECT * FROM DE_TAI DT JOIN THAM_GIA_DT TG2 ON TG2.MaDT=DT.MaDT JOIN GIAO_VIEN GV2 ON GV2.MaGV=TG2.MaGV 
		WHERE GV2.HoTen=N'Trần Trà Hương' AND
			NOT EXISTS (SELECT * FROM THAM_GIA_DT TG3 WHERE TG3.MaDT=DT.MaDT AND TG3.MaGV=TG.MaGV))
--Q63--
SELECT DISTINCT DT.TenDT
FROM THAM_GIA_DT TG JOIN DE_TAI DT ON DT.MaDT=TG.MaDT JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV
WHERE GV.MaBM='HHC' AND NOT EXISTS (SELECT * FROM GIAO_VIEN GV2 WHERE GV2.MaBM='HHC' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2  WHERE TG2.MaDT=TG.MaDT AND TG2.MaGV=GV2.MaGV))

--Q64--
SELECT DISTINCT GV.HoTen
FROM THAM_GIA_DT TG JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV 
WHERE NOT EXISTS (SELECT * FROM CONG_VIEC CV WHERE CV.MaDT='006' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaGV=TG.MaGV AND TG2.MaDT=CV.MaDT AND TG2.STT=CV.STT))

--Q65--
SELECT GV.HoTen
FROM THAM_GIA_DT TG JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV
WHERE NOT EXISTS (SELECT * FROM DE_TAI DT JOIN CHU_DE CD ON DT.MaCD=CD.MaCD WHERE CD.TenCD=N'Ứng dụng công nghệ' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaDT=DT.MaDT AND TG2.MaGV=TG.MaGV))

--Q66--
SELECT DISTINCT GV.HoTen
FROM THAM_GIA_DT TG JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV
WHERE NOT EXISTS (SELECT * FROM DE_TAI DT JOIN GIAO_VIEN GV2 ON GV2.MaGV=DT.GVCNDT WHERE GV2.HoTen=N'Trần Trà Hương' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaDT=DT.MaDT AND TG2.MaGV=TG.MaGV))

--Q67--
SELECT DT.TenDT
FROM THAM_GIA_DT TG JOIN DE_TAI DT ON DT.MaDT=TG.MaDT
WHERE NOT EXISTS (SELECT * FROM GIAO_VIEN GV JOIN BO_MON BM ON GV.MaBM=BM.MaBM WHERE BM.MaKhoa='CNTT' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaDT=TG.MaDT AND TG2.MaGV=GV.MaGV))

--Q68--
SELECT DISTINCT GV.HoTen
FROM THAM_GIA_DT TG JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV 
WHERE NOT EXISTS (SELECT * FROM CONG_VIEC CV JOIN DE_TAI DT ON CV.MaDT=DT.MaDT WHERE DT.TenDT=N'Nghiên cứu tế bào gốc' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaGV=TG.MaGV AND TG2.MaDT=CV.MaDT AND TG2.STT=CV.STT))

--Q69--
SELECT DISTINCT GV.HoTen
FROM THAM_GIA_DT TG JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV
WHERE NOT EXISTS (SELECT * FROM DE_TAI DT WHERE DT.KINHPHI>100 AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaDT=DT.MaDT AND TG2.MaGV=TG.MaGV))

--Q70--
SELECT DISTINCT DT.TenDT
FROM THAM_GIA_DT TG JOIN DE_TAI DT ON TG.MaDT=DT.MaDT
WHERE NOT EXISTS (SELECT * FROM GIAO_VIEN GV JOIN BO_MON BM ON BM.MaBM=GV.MaBM JOIN KHOA K ON K.MaKhoa=BM.MaKhoa
	WHERE K.TENKHOA=N'Sinh học' AND NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaGV=GV.MaGV AND TG2.MaDT=TG.MaDT))

--Q71--
SELECT DISTINCT GV.MaGV,GV.HoTen,GV.NgSinh
FROM THAM_GIA_DT TG JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV JOIN DE_TAI DT2 ON DT2.MaDT=TG.MaDT
WHERE DT2.TenDT=N'Ứng dụng hóa học xanh' AND NOT EXISTS (SELECT * FROM CONG_VIEC CV JOIN DE_TAI DT ON CV.MaDT=DT.MaDT WHERE DT.TenDT=N'Ứng dụng hóa học xanh' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaGV=TG.MaGV AND TG2.MaDT=CV.MaDT AND TG2.STT=CV.STT))

--Q72--
SELECT GV.MaGV,GV.HoTen, BM.TenBM, GV2.HoTen
FROM THAM_GIA_DT TG JOIN GIAO_VIEN GV ON GV.MaGV=TG.MaGV JOIN BO_MON BM ON BM.MaBM=GV.MaBM JOIN GIAO_VIEN GV2 ON GV2.MaGV=GV.GVQLCM
WHERE NOT EXISTS (SELECT * FROM DE_TAI DT JOIN CHU_DE CD ON DT.MaCD=CD.MaCD WHERE CD.TenCD=N'Nghiên cứu phát triển' AND
	NOT EXISTS (SELECT * FROM THAM_GIA_DT TG2 WHERE TG2.MaDT=DT.MaDT AND TG2.MaGV=TG.MaGV))