CREATE TABLE KHACH_HANG
(
	MaKH char(15) NOT NULL,
	Ten nvarchar(15),
	DiaChi nvarchar(50),
	DThoai char(12),

	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MaKH)
)

CREATE TABLE NHAN_VIEN
(
	MaNV char(15) NOT NULL,
	Ten nvarchar(15),
	DThoai char(12),
	Luong decimal(10,2),
	LoaiNV bit,

	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MaNV)
)

CREATE TABLE LOAI_MB 
(
	MaLoai char(15) NOT NULL,
	HangSX nvarchar(15),

	CONSTRAINT PK_LOAIMB PRIMARY KEY(MaLoai)
)

CREATE TABLE MAY_BAY
(
	SoHieu int NOT NULL,
	MaLoai char(15) NOT NULL,

	CONSTRAINT PK_MAYBAY PRIMARY KEY(SoHieu, MaLoai)
)

CREATE TABLE CHUYEN_BAY
(
	MaCB char(4) NOT NULL,
	SanBayDi char(3),
	SanBayDen char(3),
	GioDi time,
	GioDen time,

	CONSTRAINT PK_CHUYENBAY PRIMARY KEY(MaCB)
)

CREATE TABLE LICH_BAY
(
	NgayDi date NOT NULL,
	MaCB char(4) NOT NULL,
	SoHieu int,
	MaLoai char(15),

	CONSTRAINT PK_LICHBAY PRIMARY KEY(MaCB, NgayDi)
)

CREATE TABLE DAT_CHO
(
	MaKH char(15) NOT NULL,
	NgayDi date NOT NULL,
	MaCB char(4) NOT NULL,

	CONSTRAINT PK_DATCHO PRIMARY KEY(MaCB, NgayDi, MaKH)
	
)

CREATE TABLE KHA_NANG
(
	MaNV char(15) NOT NULL,
	MaLoai char(15) NOT NULL,

	CONSTRAINT PK_KHANANG PRIMARY KEY(MaNV, MaLoai)
)

CREATE TABLE PHAN_CONG
(
	MaNV char(15) NOT NULL,
	NgayDi date NOT NULL,
	MaCB char(4) NOT NULL,

	CONSTRAINT PK_PHANCONG PRIMARY KEY(MaCB, NgayDi, MaNV)
)

ALTER TABLE LICH_BAY 
ADD CONSTRAINT FK_LICHBAY_CHUYENBAY FOREIGN KEY(MaCB) REFERENCES CHUYEN_BAY(MaCB),
CONSTRAINT FK_LICHBAY_MAYBAY FOREIGN KEY(SoHieu, MaLoai) REFERENCES MAY_BAY(SoHieu, MaLoai)

ALTER TABLE PHAN_CONG
ADD CONSTRAINT FK_PHANCONG_LICHBAY FOREIGN KEY(MaCB, NgayDi) REFERENCES LICH_BAY(MaCB, NgayDi),
CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHAN_VIEN(MaNV)

ALTER TABLE DAT_CHO
ADD CONSTRAINT FK_DATCHO_LICHBAY FOREIGN KEY(MaCB, NgayDi) REFERENCES LICH_BAY(MaCB, NgayDi),
CONSTRAINT FK_DATCHO_KHACHHANG FOREIGN KEY(MaKH) REFERENCES KHACH_HANG(MaKH)

ALTER TABLE MAY_BAY
ADD CONSTRAINT FK_MAYBAY_LOAIMB FOREIGN KEY(MaLoai) REFERENCES LOAI_MB(MaLoai)

ALTER TABLE KHA_NANG
ADD CONSTRAINT FK_KHANGANG_LOAIMB FOREIGN KEY(MaLoai) REFERENCES LOAI_MB(MaLoai),
CONSTRAINT FK_KHANANG_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHAN_VIEN(MaNV)