USE [master]
GO
/****** Object:  Database [topic1]    Script Date: 26/09/2022 22:13:18 ******/
CREATE DATABASE [topic1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'topic1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\topic1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'topic1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\topic1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [topic1] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [topic1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [topic1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [topic1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [topic1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [topic1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [topic1] SET ARITHABORT OFF 
GO
ALTER DATABASE [topic1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [topic1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [topic1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [topic1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [topic1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [topic1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [topic1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [topic1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [topic1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [topic1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [topic1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [topic1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [topic1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [topic1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [topic1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [topic1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [topic1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [topic1] SET RECOVERY FULL 
GO
ALTER DATABASE [topic1] SET  MULTI_USER 
GO
ALTER DATABASE [topic1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [topic1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [topic1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [topic1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [topic1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [topic1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'topic1', N'ON'
GO
ALTER DATABASE [topic1] SET QUERY_STORE = OFF
GO
USE [topic1]
GO
/****** Object:  Table [dbo].[CT_HOA_HON]    Script Date: 26/09/2022 22:13:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CT_HOA_HON](
	[mahd] [char](15) NOT NULL,
	[masp] [char](15) NOT NULL,
	[soluong] [int] NULL,
	[dongia] [money] NULL,
 CONSTRAINT [PK_CT_HOA_HON] PRIMARY KEY CLUSTERED 
(
	[mahd] ASC,
	[masp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOA_DON]    Script Date: 26/09/2022 22:13:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOA_DON](
	[mahd] [char](15) NOT NULL,
	[ngaylap] [datetime] NULL,
	[makh] [int] NULL,
 CONSTRAINT [PK_HOA_DON] PRIMARY KEY CLUSTERED 
(
	[mahd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACH_HANG_MUA]    Script Date: 26/09/2022 22:13:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACH_HANG_MUA](
	[makh] [int] NOT NULL,
	[hoten] [varchar](30) NULL,
	[gioitinh] [char](10) NULL,
	[dthoai] [char](10) NULL,
	[diachi] [varchar](30) NULL,
 CONSTRAINT [PK_KHACH_HANG_MUA] PRIMARY KEY CLUSTERED 
(
	[makh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SAN_PHAM]    Script Date: 26/09/2022 22:13:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAN_PHAM](
	[masp] [char](15) NOT NULL,
	[tensp] [varchar](25) NULL,
	[ngaysx] [datetime] NULL,
	[dongia] [money] NULL,
 CONSTRAINT [PK_SAN_PHAM] PRIMARY KEY CLUSTERED 
(
	[masp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CT_HOA_HON]  WITH CHECK ADD  CONSTRAINT [FK_CT_HOA_HON_HOA_DON] FOREIGN KEY([mahd])
REFERENCES [dbo].[HOA_DON] ([mahd])
GO
ALTER TABLE [dbo].[CT_HOA_HON] CHECK CONSTRAINT [FK_CT_HOA_HON_HOA_DON]
GO
ALTER TABLE [dbo].[CT_HOA_HON]  WITH CHECK ADD  CONSTRAINT [FK_CT_HOA_HON_SAN_PHAM] FOREIGN KEY([masp])
REFERENCES [dbo].[SAN_PHAM] ([masp])
GO
ALTER TABLE [dbo].[CT_HOA_HON] CHECK CONSTRAINT [FK_CT_HOA_HON_SAN_PHAM]
GO
ALTER TABLE [dbo].[HOA_DON]  WITH CHECK ADD  CONSTRAINT [FK_HOA_DON_KHACH_HANG_MUA] FOREIGN KEY([makh])
REFERENCES [dbo].[KHACH_HANG_MUA] ([makh])
GO
ALTER TABLE [dbo].[HOA_DON] CHECK CONSTRAINT [FK_HOA_DON_KHACH_HANG_MUA]
GO
USE [master]
GO
ALTER DATABASE [topic1] SET  READ_WRITE 
GO
